print("Data Types")
print("Tuples")
print("Accessing items a tuple with slicing")
tup1=('a','b','c','d','e','f')
print(tup1[:5])
print(tup1[4:])
print(tup1[2:6:2])
print(tup1[2:4])
print(tup1[-5:-1])
