print("Data Types")
print("Tuples")
tup1=(20,4.5,True,"hello",[1,3,5,7])
print(tup1,"is of type",type(tup1))
tup2=()
print(tup2,"is of type",type(tup2))
tup3=tuple(['one','two','three'])
print(tup3,"is of type",type(tup3))
tup4=tuple()
print(tup4,"is of type",type(tup4))
