print("Data Types")
print("Tuples")
print("Create a tuple with a single item")
tup1=(5)
print(tup1,"is of type",type(tup1))
tup1=(5,)
print(tup1,"is of type",type(tup1))
tup2=tuple("Hello")
print(tup2,"is of type",type(tup2))
tup3=tuple(15,)
print(tup3,"is of type",type(tup3))
tup4=(2,4,6,8,10)
print('There are',len(tup4),'items in',tup4)
